name:  🖥 API 🐞 Bug Report
description: Report problems and errors in PyPackIT-Test1's API.
body:
- type: markdown
  attributes:
    value: "<p align=\"justify\">\n  Thank you for providing feedback on PyPackIT
      Test1;\n  we greatly appreciate your contribution!\n  Before submitting a ticket,\n\
      \  please take a moment to review and accept our terms and conditions.\n</p>"
- type: markdown
  attributes:
    value: "<br>\n\n## 🤝 Terms and Conditions\n"
- type: markdown
  attributes:
    value: "### ⛔ Choosing the Right Form\n\n<p align=\"justify\">\n  Please note
      that this form is specifically for reporting a <b>non-security-related bug in
      PyPackIT-Test1's API</b>, i.e. an unexpected behavior or result in PyPackIT-Test1's
      Python application programming interface.,\n  For other types of issues and
      requests, select the appropriate form\n  from the <a href=\"https://github.com/AAriam/PyPackIT-Test1/issues/new/choose\"\
      >issue template chooser</a>.\n  If you are unsure about which form to choose
      or have another inquiry,\n  please open a discussion in our <a href=\"https://github.com/AAriam/PyPackIT-Test1/discussions\"\
      >discussion forum</a>.\n</p>\n"
- type: markdown
  attributes:
    value: "### ⚠️ Verifying the Bug\n\n<p align=\"justify\">\n  Before submitting
      a report, please make sure that you are following our\n  <a href=\"https://AAriam.github.io/PyPackIT-Test1/contribute\"\
      >Bug Report Guidelines</a> to verify that:\n</p>\n\n- <p align=\"justify\">The
      issue you are experiencing is in fact a bug, and not a documented expected behavior.</p>\n
      - <p align=\"justify\">The bug is reproducible in the latest version of the
      release, and has not yet been reported.</p>\n"
- type: markdown
  attributes:
    value: "### ℹ️ Choosing the Right Title\n\n<p align=\"justify\">Please write a
      concise and descriptive title and\nuse relevant keywords to help others find
      the issue.</p>\n"
- type: markdown
  attributes:
    value: '### ✅ Agreements'
- type: checkboxes
  id: terms
  attributes:
    label: 'To submit an issue, please agree to the following terms and conditions:'
    options:
    - label: "I confirm that I am following PyPackIT Test1's [Contribution Guidelines](https://AAriam.github.io/PyPackIT-Test1/contribute).<!--
        ISSUE-ID: pkg_api_fix -->"
      required: true
    - label: I agree to follow PyPackIT Test1's [Code of Conduct](https://github.com/AAriam/PyPackIT-Test1/blob/main/CODE_OF_CONDUCT.md).
      required: true
- type: markdown
  attributes:
    value: '### 🧑‍💻️ Collaboration'
- type: checkboxes
  id: collab
  attributes:
    label: "Thank you again for filling out this ticket.\nIf you are willing to collaborate
      on its implementation,\nplease select the option below.\n"
    options:
    - label: I am willing to collaborate on this issue and submit a pull request.
      required: false
- type: markdown
  attributes:
    value: "<br>\n\n## 🎛 Environment Specifications\n"
- type: dropdown
  id: os
  attributes:
    label: Operating System
    description: "Please select all operating systems on which you have encountered
      the bug.\n"
    multiple: true
    options:
    - Linux
    - MacOS
    - Windows
  validations:
    required: true
- type: dropdown
  id: python_version
  attributes:
    label: Python Version
    description: "Please select all Python versions in which you have encountered
      the bug.\n"
    multiple: true
    options:
    - '3.13'
    - '3.12'
    - '3.11'
    - '3.10'
    default: 0
  validations:
    required: true
- type: dropdown
  id: package_manager
  attributes:
    label: Package Manager
    description: "Please select the package manager used to download and install PyPackIT
      Test1.\n"
    multiple: false
    options:
    - pip
    default: 0
  validations:
    required: true
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: "Please provide the details of all installed packages and their exact
      versions in the environment where you have encountered the bug. Follow the instructions
      below based on the package manager you have selected:\n1. **`pip`**: Run `pip
      freeze > requirements.txt` in your terminal within the environment, and copy
      the contents of the generated `requirements.txt` file here.\n2. **`conda`**:
      Run `conda env export > environment.yml` in your terminal within the environment
      (or alternatively `conda env export -n {YOUR_ENVIRONMENT_NAME} > environment.yml`),
      and copy the contents of the generated `environment.yml` file here."
    render: yaml
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br>\n\n## 🐞 Bug Report\n"
- type: dropdown
  id: version
  attributes:
    label: Version
    description: "Please select all relevant PyPackIT Test1 versions.\n"
    multiple: true
    options:
    - 0.0.9
    default: 0
  validations:
    required: true
- type: dropdown
  id: entrypoint
  attributes:
    label: API Entry Point
    description: Please select the relevant API entry point.
    multiple: false
    options:
    - pypackit_test1
    default: 0
  validations:
    required: true
- type: input
  id: endpoint
  attributes:
    label: Fully Qualified Name
    description: Please provide the fully qualified name (minus the entry point) of
      the relevant API endpoint. For example, for a method at `pypackit_test1.module_name.ClassName.method_name`
      in the entry point `pypackit_test1`, you should write `module_name.ClassName.method_name`.
    placeholder: module_name.ClassName.method_name
  validations:
    required: true
- type: textarea
  id: summary
  attributes:
    label: Summary
    description: Please provide a summary of the issue.
  validations:
    required: true
- type: textarea
  id: test_case
  attributes:
    label: Test Case
    description: "Please provide a [test case](https://docs.pytest.org/en/stable/getting-started.html)
      that demonstrates the bug:\n- At the top of the code block below, add the minimum
      number of imports required to reproduce the bug.\n- Replace the ellipsis (`...`)
      in the `test` function with a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)
      (MRE). Use [`assert` statements](https://docs.pytest.org/en/stable/how-to/assert.html)
      to specify the expected results."
    value: "import pypackit_test1\n\n\ndef test():\n    ...\n"
    render: python
  validations:
    required: true
